name: MacStadium CI

on:
  push:
    branches:
      - master


permissions: {}

jobs:
  macfuse:
    permissions:
      contents: read
    runs-on: macstadium
    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: ./.github/actions/macfuse-ci
