name: MacStadium CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  macfuse:
    runs-on: macstadium
    environment: macstadium   # approval gate for security
    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: ./.github/actions/macfuse-ci
